import {openDB,type DBSchema} from "idb";import type {ArchivedMessage,Conversation,ImportRecord,Participant} from "../shared/types";
interface ArchiveDB extends DBSchema{messages:{key:string;value:ArchivedMessage;indexes:{"by-conversation":string;"by-captured-at":number}};conversations:{key:string;value:Conversation};participants:{key:string;value:Participant;indexes:{"by-conversation":string}};imports:{key:string;value:ImportRecord;indexes:{"by-conversation":string}}}
const dbPromise=openDB<ArchiveDB>("wa-archive",2,{upgrade(db,oldVersion){if(oldVersion<1){const s=db.createObjectStore("messages",{keyPath:"id"});s.createIndex("by-conversation","conversationId");s.createIndex("by-captured-at","capturedAt")}if(oldVersion<2){db.createObjectStore("conversations",{keyPath:"id"});const p=db.createObjectStore("participants",{keyPath:"id"});p.createIndex("by-conversation","conversationId");const i=db.createObjectStore("imports",{keyPath:"id"});i.createIndex("by-conversation","conversationId")}}});
export async function saveMessages(messages:ArchivedMessage[]){const db=await dbPromise;const tx=db.transaction("messages","readwrite");let added=0;for(const message of messages){if(!(await tx.store.get(message.id))){added++;await tx.store.put(message)}}await tx.done;return{added,total:messages.length,duplicates:messages.length-added}}
export async function getAllMessages(){return(await dbPromise).getAll("messages")}
export async function getConversationMessages(id:string){return(await dbPromise).getAllFromIndex("messages","by-conversation",id)}
export async function upsertConversation(c:Conversation){await(await dbPromise).put("conversations",c)}
export async function getConversation(id:string){return(await dbPromise).get("conversations",id)}
export async function getConversations(){return(await dbPromise).getAll("conversations")}
export async function saveParticipants(rows:Participant[]){const db=await dbPromise;const tx=db.transaction("participants","readwrite");for(const r of rows)await tx.store.put(r);await tx.done}
export async function addImport(row:ImportRecord){await(await dbPromise).put("imports",row)}
export async function deleteConversation(id:string){const db=await dbPromise;const tx=db.transaction(["messages","conversations","participants","imports"],"readwrite");for(const m of await tx.objectStore("messages").index("by-conversation").getAllKeys(id))await tx.objectStore("messages").delete(m);for(const p of await tx.objectStore("participants").index("by-conversation").getAllKeys(id))await tx.objectStore("participants").delete(p);for(const i of await tx.objectStore("imports").index("by-conversation").getAllKeys(id))await tx.objectStore("imports").delete(i);await tx.objectStore("conversations").delete(id);await tx.done}
export async function renameConversation(id:string,title:string){const db=await dbPromise;const c=await db.get("conversations",id);if(c)await db.put("conversations",{...c,title,updatedAt:Date.now()});const rows=await db.getAllFromIndex("messages","by-conversation",id);const tx=db.transaction("messages","readwrite");for(const m of rows)await tx.store.put({...m,conversationTitle:title});await tx.done}