import {parseVisibleConversation} from "./parser";
import {conversationRoot} from "./selectors";
declare global {interface Window {__waArchiveLoaded?:boolean}}
if(!window.__waArchiveLoaded){
window.__waArchiveLoaded=true;
let observer:MutationObserver|null=null,rootWatcher:MutationObserver|null=null,watching=false,scanTimer=0;
let running=false,paused=false,cancelled=false;
const log=(...args:unknown[])=>console.info("[WA Archive]",...args);
async function capture(){const messages=parseVisibleConversation();if(!messages.length)return{ok:true,added:0,total:0,duplicates:0,conversation:null};const result=await chrome.runtime.sendMessage({type:"WA_ARCHIVE_SAVE_MESSAGES",messages});if(!result?.ok)throw new Error(result?.error||"Falha ao salvar mensagens");return{...result,conversation:messages[0].conversationTitle}}
function attach(){observer?.disconnect();observer=null;const root=conversationRoot();if(!root)return;observer=new MutationObserver(()=>{clearTimeout(scanTimer);scanTimer=window.setTimeout(()=>void capture().catch(console.warn),500)});observer.observe(root,{childList:true,subtree:true});log("Watching conversation",root.querySelector("header [title]")?.getAttribute("title"))}
function watch(){watching=true;attach();rootWatcher?.disconnect();rootWatcher=new MutationObserver(()=>{if(watching&&(!observer||!document.contains(conversationRoot())))attach()});rootWatcher.observe(document.body,{childList:true,subtree:true})}
function stop(){watching=false;observer?.disconnect();observer=null;rootWatcher?.disconnect();rootWatcher=null;clearTimeout(scanTimer)}
function scroller(){const root=conversationRoot();if(!root)return null;const elements=[root,...root.querySelectorAll<HTMLElement>("*")];return elements.filter(e=>e.scrollHeight>e.clientHeight+150&&getComputedStyle(e).overflowY!=="hidden").sort((a,b)=>b.scrollHeight-a.scrollHeight)[0] as HTMLElement|undefined}
async function history(send:(v:unknown)=>void){if(running)throw new Error("Captura de histórico já em andamento");const root=conversationRoot();if(!root)throw new Error("Abra uma conversa primeiro");const title=root.querySelector("header [title]")?.getAttribute("title")||"";running=true;paused=false;cancelled=false;let added=0,duplicates=0,rounds=0,stalled=0;try{while(!cancelled&&rounds<2000){while(paused&&!cancelled)await new Promise(r=>setTimeout(r,300));if(cancelled)break;if(!document.contains(root)||((conversationRoot()?.querySelector("header [title]")?.getAttribute("title")||"")!==title))throw new Error("Conversa alterada durante a captura");const result=await capture();added+=result.added;duplicates+=result.duplicates;const box=scroller();if(!box)throw new Error("Área de rolagem não encontrada");const before=box.scrollTop;box.scrollTop=Math.max(0,before-Math.max(box.clientHeight*0.85,350));await new Promise(r=>setTimeout(r,850));rounds++;const after=box.scrollTop;if(after===before&&result.added===0)stalled++;else stalled=0;await chrome.storage.local.set({waArchiveHistory:{running:true,added,duplicates,rounds,stalled,title}});if(stalled>=5)break}send({ok:true,added,duplicates,rounds,cancelled})}catch(e){send({ok:false,error:String(e),added,rounds})}finally{running=false;await chrome.storage.local.set({waArchiveHistory:{running:false,added,duplicates,rounds,title,cancelled}})}}
chrome.runtime.onMessage.addListener((m,_sender,respond)=>{try{if(m?.type==="WA_ARCHIVE_PING"){respond({ok:true,conversation:!!conversationRoot(),running,paused});return}if(m?.type==="WA_ARCHIVE_SCAN"){capture().then(respond).catch(e=>respond({ok:false,error:String(e)}));return true}if(m?.type==="WA_ARCHIVE_WATCH"){watch();respond({ok:true});return}if(m?.type==="WA_ARCHIVE_STOP"){stop();cancelled=true;respond({ok:true});return}if(m?.type==="WA_ARCHIVE_HISTORY"){void history(respond);return true}if(m?.type==="WA_ARCHIVE_PAUSE"){paused=true;respond({ok:true});return}if(m?.type==="WA_ARCHIVE_RESUME"){paused=false;respond({ok:true});return}}catch(e){respond({ok:false,error:String(e)})}});
log("Content script ready");
}