import type {ArchivedMessage,ConversationSummary} from "../shared/types";
export const SESSION_GAP_MS=4*60*60*1000;const time=(m:ArchivedMessage)=>m.messageAt??m.capturedAt;const valid=(m:ArchivedMessage)=>m.type!=="system";
export interface ArchiveAnalytics{total:number;conversations:number;participants:number;incoming:number;outgoing:number;outgoingShare:number;topParticipants:Array<{name:string;messages:number}>;hours:Array<{hour:number;messages:number}>;days:Array<{day:string;messages:number}>}
export function summarize(messages:ArchivedMessage[]):ConversationSummary[]{const map=new Map<string,ConversationSummary>();for(const m of messages){const t=time(m),s=map.get(m.conversationId)??{id:m.conversationId,title:m.conversationTitle,messageCount:0,incoming:0,outgoing:0,participants:{},firstCapturedAt:t,lastCapturedAt:t};s.messageCount++;if(m.direction==="incoming")s.incoming++;if(m.direction==="outgoing")s.outgoing++;if(valid(m))s.participants[m.sender]=(s.participants[m.sender]??0)+1;s.firstCapturedAt=Math.min(s.firstCapturedAt??t,t);s.lastCapturedAt=Math.max(s.lastCapturedAt??t,t);map.set(m.conversationId,s)}return[...map.values()].sort((a,b)=>b.messageCount-a.messageCount)}
export function analyze(messages:ArchivedMessage[]):ArchiveAnalytics{const rows=messages.filter(valid),incoming=rows.filter(m=>m.direction==="incoming").length,outgoing=rows.filter(m=>m.direction==="outgoing").length,people=new Map<string,number>(),hours=Array.from({length:24},(_,hour)=>({hour,messages:0})),days=new Map<string,number>();for(const m of rows){people.set(m.sender,(people.get(m.sender)??0)+1);const d=new Date(time(m));hours[d.getHours()].messages++;const key=d.toISOString().slice(0,10);days.set(key,(days.get(key)??0)+1)}return{total:messages.length,conversations:new Set(messages.map(m=>m.conversationId)).size,participants:people.size,incoming,outgoing,outgoingShare:incoming+outgoing?Math.round(outgoing/(incoming+outgoing)*100):0,topParticipants:[...people].map(([name,count])=>({name,messages:count})).sort((a,b)=>b.messages-a.messages).slice(0,10),hours,days:[...days].map(([day,count])=>({day,messages:count})).sort((a,b)=>a.day.localeCompare(b.day))}}
export function median(values:number[]){if(!values.length)return null;const s=[...values].sort((a,b)=>a-b),i=Math.floor(s.length/2);return s.length%2?s[i]:(s[i-1]+s[i])/2}
export interface ResponseStats{sessions:number;startedByYou:number;startedByOthers:number;yourResponseMs:number|null;theirResponseMs:number|null}
export function responseStats(messages:ArchivedMessage[]):ResponseStats{let sessions=0,startedByYou=0,startedByOthers=0;const yours:number[]=[],theirs:number[]=[];const groups=new Map<string,ArchivedMessage[]>();for(const m of messages.filter(m=>valid(m)&&m.messageAt)){const a=groups.get(m.conversationId)??[];a.push(m);groups.set(m.conversationId,a)}for(const rows of groups.values()){rows.sort((a,b)=>time(a)-time(b));let blocks:ArchivedMessage[][]=[];for(const m of rows){const last=blocks.at(-1)?.at(-1);if(!last||time(m)-time(last)>=SESSION_GAP_MS||m.direction!==last.direction)blocks.push([m]);else blocks.at(-1)!.push(m)}for(let i=0;i<blocks.length;i++){const block=blocks[i],first=block[0],prev=blocks[i-1];if(!prev||time(first)-time(prev.at(-1)!)>=SESSION_GAP_MS){sessions++;if(first.direction==="outgoing")startedByYou++;else if(first.direction==="incoming")startedByOthers++;continue}const gap=time(first)-time(prev.at(-1)!);if(first.direction==="outgoing"&&prev[0].direction==="incoming")yours.push(gap);if(first.direction==="incoming"&&prev[0].direction==="outgoing")theirs.push(gap)}}return{sessions,startedByYou,startedByOthers,yourResponseMs:median(yours),theirResponseMs:median(theirs)}}
export interface InteractionEdge{from:string;to:string;count:number}
export function interactionEdges(messages:ArchivedMessage[]):InteractionEdge[]{const edges=new Map<string,InteractionEdge>(),chats=new Map<string,ArchivedMessage[]>();for(const m of messages.filter(m=>valid(m)&&m.messageAt)){const a=chats.get(m.conversationId)??[];a.push(m);chats.set(m.conversationId,a)}for(const rows of chats.values()){rows.sort((a,b)=>time(a)-time(b));for(let i=1;i<rows.length;i++){const a=rows[i-1],b=rows[i];if(a.sender===b.sender||time(b)-time(a)>=SESSION_GAP_MS)continue;const key=a.sender+" → "+b.sender,e=edges.get(key)??{from:a.sender,to:b.sender,count:0};e.count++;edges.set(key,e)}}return[...edges.values()].sort((a,b)=>b.count-a.count).slice(0,25)}
export function reciprocity(edges:InteractionEdge[]){let total=0,mutual=0;const map=new Map(edges.map(e=>[e.from+"\0"+e.to,e.count]));for(const e of edges){total+=e.count;mutual+=Math.min(e.count,map.get(e.to+"\0"+e.from)??0)}return total?Math.round(mutual/total*100):0}