import type {ArchivedMessage,ConversationSummary} from "../shared/types";
export interface ArchiveAnalytics{total:number;conversations:number;participants:number;incoming:number;outgoing:number;outgoingShare:number;topParticipants:Array<{name:string;messages:number}>;hours:Array<{hour:number;messages:number}>;days:Array<{day:string;messages:number}>}
const time=(m:ArchivedMessage)=>m.messageAt??m.capturedAt;
export function summarize(messages:ArchivedMessage[]):ConversationSummary[]{const map=new Map<string,ConversationSummary>();for(const m of messages){const t=time(m);const s=map.get(m.conversationId)??{id:m.conversationId,title:m.conversationTitle,messageCount:0,incoming:0,outgoing:0,participants:{},firstCapturedAt:t,lastCapturedAt:t};s.messageCount++;if(m.direction==="incoming")s.incoming++;if(m.direction==="outgoing")s.outgoing++;s.participants[m.sender]=(s.participants[m.sender]??0)+1;s.firstCapturedAt=Math.min(s.firstCapturedAt??t,t);s.lastCapturedAt=Math.max(s.lastCapturedAt??t,t);map.set(m.conversationId,s)}return[...map.values()].sort((a,b)=>b.messageCount-a.messageCount)}
export function analyze(messages:ArchivedMessage[]):ArchiveAnalytics{const incoming=messages.filter(m=>m.direction==="incoming").length;const outgoing=messages.filter(m=>m.direction==="outgoing").length;const people=new Map<string,number>();const hours=Array.from({length:24},(_,hour)=>({hour,messages:0}));const days=new Map<string,number>();for(const m of messages){people.set(m.sender,(people.get(m.sender)??0)+1);const d=new Date(time(m));hours[d.getHours()].messages++;const key=d.toISOString().slice(0,10);days.set(key,(days.get(key)??0)+1)}return{total:messages.length,conversations:new Set(messages.map(m=>m.conversationId)).size,participants:people.size,incoming,outgoing,outgoingShare:incoming+outgoing?Math.round(outgoing/(incoming+outgoing)*100):0,topParticipants:[...people].map(([name,count])=>({name,messages:count})).sort((a,b)=>b.messages-a.messages).slice(0,10),hours,days:[...days].map(([day,count])=>({day,messages:count})).sort((a,b)=>a.day.localeCompare(b.day))}}
export interface ResponseStats{sessions:number;startedByYou:number;startedByOthers:number;yourResponseMs:number|null;theirResponseMs:number|null}
function middle(values:number[]){if(!values.length)return null;const sorted=[...values].sort((a,b)=>a-b);return sorted[Math.floor(sorted.length/2)]}
export function responseStats(messages:ArchivedMessage[]):ResponseStats{const rows=messages.filter(m=>m.messageAt).sort((a,b)=>time(a)-time(b));let sessions=0,startedByYou=0,startedByOthers=0;const yours:number[]=[],theirs:number[]=[];let previous:ArchivedMessage|undefined;for(const current of rows){const gap=previous?time(current)-time(previous):Infinity;if(!previous||previous.conversationId!==current.conversationId||gap>1800000){sessions++;if(current.direction==="outgoing")startedByYou++;else startedByOthers++}else if(current.sender!==previous.sender){if(current.direction==="outgoing")yours.push(gap);else if(previous.direction==="outgoing")theirs.push(gap)}previous=current}return{sessions,startedByYou,startedByOthers,yourResponseMs:middle(yours),theirResponseMs:middle(theirs)}}
export interface InteractionEdge{from:string;to:string;count:number}
export function interactionEdges(messages:ArchivedMessage[]):InteractionEdge[]{const edges=new Map<string,InteractionEdge>();const chats=new Map<string,ArchivedMessage[]>();for(const m of messages){if(!m.messageAt)continue;const list=chats.get(m.conversationId)??[];list.push(m);chats.set(m.conversationId,list)}for(const list of chats.values()){list.sort((a,b)=>time(a)-time(b));for(let i=1;i<list.length;i++){const a=list[i-1],b=list[i];if(a.sender===b.sender||time(b)-time(a)>1800000)continue;const key=a.sender+" → "+b.sender;const edge=edges.get(key)??{from:a.sender,to:b.sender,count:0};edge.count++;edges.set(key,edge)}}return[...edges.values()].sort((a,b)=>b.count-a.count).slice(0,25)}
export function reciprocity(edges:InteractionEdge[]){let total=0,mutual=0;for(const edge of edges){total+=edge.count;const reverse=edges.find(x=>x.from===edge.to&&x.to===edge.from)?.count??0;mutual+=Math.min(edge.count,reverse)}return total?Math.round(mutual/total*100):0}