import {getAllMessages} from "./database/db";import {analyze,summarize} from "./analytics/summary";import type {ArchivedMessage} from "./shared/types";
const all=await getAllMessages();const search=document.querySelector<HTMLInputElement>("#search")!;const select=document.querySelector<HTMLSelectElement>("#conversation")!;
for(const s of summarize(all)){const o=document.createElement("option");o.value=s.id;o.textContent=s.title;select.append(o)}
const esc=(v:string)=>{const d=document.createElement("div");d.textContent=v;return d.innerHTML};const stamp=(m:ArchivedMessage)=>new Date(m.messageAt??m.capturedAt).toLocaleString("pt-BR");
function filtered(){const q=search.value.trim().toLocaleLowerCase();return all.filter(m=>(!select.value||m.conversationId===select.value)&&(!q||[m.text,m.sender,m.conversationTitle].some(v=>v.toLocaleLowerCase().includes(q))))}
function render(){const messages=filtered();const a=analyze(messages);const summaries=summarize(messages);
document.querySelector("#metrics")!.innerHTML="<article><strong>"+a.total+"</strong><span>mensagens</span></article><article><strong>"+a.conversations+"</strong><span>conversas</span></article><article><strong>"+a.participants+"</strong><span>participantes</span></article><article><strong>"+a.outgoingShare+"%</strong><span>enviadas por você</span></article>";
const maxHour=Math.max(1,...a.hours.map(x=>x.messages));document.querySelector("#hours")!.innerHTML=a.hours.map(x=>"<div class=\"bar-col\" title=\""+x.hour+"h · "+x.messages+" mensagens\"><div class=\"bar\" style=\"height:"+Math.max(2,Math.round(x.messages/maxHour*120))+"px\"></div><small>"+String(x.hour).padStart(2,"0")+"</small></div>").join("");
const maxPerson=Math.max(1,...a.topParticipants.map(x=>x.messages));document.querySelector("#participants")!.innerHTML=a.topParticipants.length?a.topParticipants.map((x,i)=>"<div class=\"rank\"><span><b>"+(i+1)+".</b> "+esc(x.name)+"</span><div class=\"progress\"><i style=\"width:"+Math.round(x.messages/maxPerson*100)+"%\"></i></div><strong>"+x.messages+"</strong></div>").join(""):"<p class=\"muted\">Sem dados.</p>";
const recent=a.days.slice(-30);const maxDay=Math.max(1,...recent.map(x=>x.messages));document.querySelector("#days")!.innerHTML=recent.map(x=>"<div class=\"day\" title=\""+x.day+" · "+x.messages+"\"><i style=\"height:"+Math.max(4,Math.round(x.messages/maxDay*100))+"%\"></i><small>"+x.day.slice(5)+"</small></div>").join("");
document.querySelector("#conversations")!.innerHTML=summaries.length?summaries.map(s=>"<button class=\"card conversation-card\" data-id=\""+s.id+"\"><h3>"+esc(s.title)+"</h3><strong>"+s.messageCount+"</strong> mensagens<p>"+s.outgoing+" enviadas · "+s.incoming+" recebidas · "+Object.keys(s.participants).length+" participantes</p></button>").join(""):"<div class=\"empty\">Nenhum resultado.</div>";
const ordered=[...messages].sort((a,b)=>(b.messageAt??b.capturedAt)-(a.messageAt??a.capturedAt)).slice(0,300);document.querySelector("#result-count")!.textContent=messages.length+" resultados";document.querySelector("#timeline")!.innerHTML=ordered.length?ordered.map(m=>"<article class=\"message "+m.direction+"\"><div><strong>"+esc(m.sender)+"</strong><span>"+esc(m.conversationTitle)+" · "+stamp(m)+"</span></div><p>"+esc(m.text)+"</p></article>").join(""):"<div class=\"empty\">Nenhuma mensagem encontrada.</div>";
document.querySelectorAll<HTMLElement>(".conversation-card").forEach(el=>el.onclick=()=>{select.value=el.dataset.id||"";render();window.scrollTo({top:0,behavior:"smooth"})})}
search.addEventListener("input",render);select.addEventListener("change",render);render();
document.querySelector("#export")?.addEventListener("click",()=>{const blob=new Blob([JSON.stringify(filtered(),null,2)],{type:"application/json"});const a=document.createElement("a");a.href=URL.createObjectURL(blob);a.download="wa-archive-"+new Date().toISOString().slice(0,10)+".json";a.click();URL.revokeObjectURL(a.href)});